### PR TITLE
Support Python 3.12 wheels

### LINKED ISSUE #156: Not available for Python 3.12
It seems like there is no available versions for Python 3.12 in PyPI. When can we expect that to be available?

Logs from a CI run of a container based on `docker.io/library/python:3.12` 
```
 > [8/8] RUN pip install -r requirements.txt:
2.857 ERROR: Could not find a version that satisfies the requirement pulsar-client>=3.1.0 (from versions: none)
2.858 ERROR: No matching distribution found for pulsar-client>=3.1.0
```
This worked fine with Python 3.11.

### PR DESCRIPTION
**Pull request by merlimat**
Fix #156

### CODE REVIEW

**Review by BewareMyPower — APPROVED** [review]

**Comment by ifduyue** [comment]
When will this be released?

**Comment by BewareMyPower** [comment]
Yes, it will be included in the next 3.4.0 release

**Comment by ifduyue** [comment]
I see there is https://github.com/apache/pulsar-client-python/releases/tag/v3.4.0-candidate-1, I suppose we can expect 3.4.0 release this week?

**Comment by BewareMyPower** [comment]
I didn't see a vote for this candidate [here](https://lists.apache.org/list?dev@pulsar.apache.org:lte=1M:vote). Generally, we need a vote that must be open for at least 72 hours until 3 binding +1s and then promote the candidate to a formal release.

@RobertIndie Is there anything that blocks the release or did you just forget the vote?

**Comment by RobertIndie** [comment]
@BewareMyPower It's blocked by the release CI: https://github.com/apache/pulsar-client-python/actions/runs/7269467100/job/19807133709. I'm currently fixing it.

**Pull request merged**
