### PR TITLE
Issue #31 - Access name attribute of any type object

### PR DESCRIPTION
**Pull request by erichare**
Addresses Issue #31 - we should access a string representation of the given object rather than assuming that the object itself can be concatenated with a string.

### CODE REVIEW

**Review by BewareMyPower — COMMENTED** [review]
We can also migrate other changes from https://github.com/apache/pulsar/pull/16459? For example, `CustomEnum` also concatenate `enum_type` and a string.

**Comment by erichare** [comment]
@BewareMyPower i agree about CustomEnum. I was less sure about the Array change in that PR - The array can be of primitive types, such as a str itself, right? do we need to check whether there exists a `__name__` attribute, otherwise just try to coerce directly to a str if not? Basically just wasn't sure if we can always assume it'll have that attribute... the original PR seemed to be closed and requested not to merge because of that same issue

**Comment by BewareMyPower** [comment]
> do we need to check whether there exists a __name__ attribute,

If so, we can create a helper function to return `s.__name__` or fall back to `str(s)`.

**Comment by erichare** [comment]
@BewareMyPower thanks! I just pushed a new commit which tries to backport those other instances from the closed PR, using a helper function. Let me know if this looks okay.

**Review by eolivelli — APPROVED** [review]
+1

**Pull request merged**
